fix:pushing firmware

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -21,64 +21,67 @@ jobs:
     steps:
       - name: Build docker image
         id: docker_build
-        uses: qualcomm-linux/video-driver/.github/actions/build_docker_image@fix-mounting
+        uses: qualcomm-linux/video-driver/.github/actions/build_docker_image@fix-mounting-3
+
+      - name: checkout
+        uses: actions/checkout@v5
 
       - name: Sync codebase
-        uses: qualcomm-linux/video-driver/.github/actions/sync@fix-mounting
+        uses: qualcomm-linux/video-driver/.github/actions/sync@fix-mounting-3
         with:
           event_name: ${{ github.event_name }}
           pr_ref: ${{ github.event.pull_request.head.ref }}
           pr_repo: ${{ github.event.pull_request.head.repo.full_name }}
           base_ref: ${{ github.ref_name }}
 
-      - name: Build ${{ matrix.build_matrix.machine }}
-        uses: qualcomm-linux/video-driver/.github/actions/build@fix-mounting
-        with:
-          docker_image: ${{ steps.docker_build.outputs.image_name }}
-          kas_file: ${{ matrix.build_matrix.kas_file }}
-          build_command: "bitbake qcom-multimedia-proprietary-image"
-        env:
-          machine: ${{ matrix.build_matrix.machine }}
+      # - name: Build ${{ matrix.build_matrix.machine }}
+      #   uses: qualcomm-linux/video-driver/.github/actions/build@fix-mounting-3
+      #   with:
+      #     docker_image: ${{ steps.docker_build.outputs.image_name }}
+      #     kas_file: ${{ matrix.build_matrix.kas_file }}
+      #     build_command: "bitbake qcom-multimedia-proprietary-image"
+      #   env:
+      #     machine: ${{ matrix.build_matrix.machine }}
 
-      - name: Prepare .qcomflash files for S3 upload
-        run: |
-          set -e
-          workspace=${{ github.workspace }}
-          machine="${{ matrix.build_matrix.machine }}"
-          symlink_path="$workspace/build/tmp/deploy/images/$machine/qcom-multimedia-proprietary-image-${machine}.rootfs.qcomflash"
+      # - name: Prepare .qcomflash files for S3 upload
+      #   run: |
+      #     set -e
+      #     workspace=${{ github.workspace }}
+      #     machine="${{ matrix.build_matrix.machine }}"
+      #     symlink_path="$workspace/build/tmp/deploy/images/$machine/qcom-multimedia-proprietary-image-${machine}.rootfs.qcomflash"
 
-          if [ ! -L "$symlink_path" ]; then
-            echo "❌ Symlink not found: $symlink_path"
-            exit 1
-          fi
+      #     if [ ! -L "$symlink_path" ]; then
+      #       echo "❌ Symlink not found: $symlink_path"
+      #       exit 1
+      #     fi
 
-          resolved_dir=$(readlink -f "$symlink_path")
+      #     resolved_dir=$(readlink -f "$symlink_path")
 
-          if [ ! -d "$resolved_dir" ]; then
-            echo "❌ Resolved .qcomflash directory not found: $resolved_dir"
-            exit 1
-          fi
-          cd $resolved_dir
-          ls -larth
-          mkdir -p "$workspace/artifacts"
-          touch "$workspace/artifacts/tar_list.txt"
+      #     if [ ! -d "$resolved_dir" ]; then
+      #       echo "❌ Resolved .qcomflash directory not found: $resolved_dir"
+      #       exit 1
+      #     fi
+      #     cd $resolved_dir
+      #     ls -larth
+      #     mkdir -p "$workspace/artifacts"
+      #     touch "$workspace/artifacts/tar_list.txt"
 
-          echo "📥 Archiving files in resolved directory: $resolved_dir"
-          find . -type f > "$workspace/artifacts/tar_list.txt"
+      #     echo "📥 Archiving files in resolved directory: $resolved_dir"
+      #     find . -type f > "$workspace/artifacts/tar_list.txt"
 
-          if [ ! -s "$workspace/artifacts/tar_list.txt" ]; then
-            echo "⚠️ No files found to archive. Skipping tarball creation."
-            exit 1
-          fi
+      #     if [ ! -s "$workspace/artifacts/tar_list.txt" ]; then
+      #       echo "⚠️ No files found to archive. Skipping tarball creation."
+      #       exit 1
+      #     fi
 
-          tarball="${machine}_qcomflash.tar.gz"
-          tar -cJf "$tarball" -T "$workspace/artifacts/tar_list.txt"
-          mv "$tarball" ${{ github.workspace }}
+      #     tarball="${machine}_qcomflash.tar.gz"
+      #     tar -cJf "$tarball" -T "$workspace/artifacts/tar_list.txt"
+      #     mv "$tarball" ${{ github.workspace }}
 
-          echo "✅ Tarball created: $tarball"
+      #     echo "✅ Tarball created: $tarball"
 
       - name: Generate Iris test app
-        uses: qualcomm-linux/video-driver/.github/actions/generate_iris_test_app@fix-mounting
+        uses: qualcomm-linux/video-driver/.github/actions/generate_iris_test_app@fix-mounting-3
         with:
           docker_image: ${{ steps.docker_build.outputs.image_name }}
 
@@ -89,25 +92,25 @@ jobs:
           tar -cJf ${{ matrix.build_matrix.machine }}_irisTestApp.tar.gz build/
           echo "Tar for testApp created successfully!"
 
-      - name: Upload build artifacts to S3
-        id: upload-artifacts
-        uses: qualcomm-linux/video-driver/.github/actions/aws_s3_helper@fix-mounting
-        with:
-          s3_bucket: qli-prd-video-gh-artifacts
-          local_file: ${{ github.workspace }}/${{ matrix.build_matrix.machine }}_qcomflash.tar.gz
-          mode: single-upload
-        env:
-          machine: "${{ matrix.build_matrix.machine }}"
+      # - name: Upload build artifacts to S3
+      #   id: upload-artifacts
+      #   uses: ./.github/actions/aws_s3_helper
+      #   with:
+      #     s3_bucket: qli-prd-video-gh-artifacts
+      #     local_file: ${{ github.workspace }}/${{ matrix.build_matrix.machine }}_qcomflash.tar.gz
+      #     mode: single-upload
+      #   env:
+      #     machine: "${{ matrix.build_matrix.machine }}"
 
       - name: Upload testApp to S3
-        uses: qualcomm-linux/video-driver/.github/actions/aws_s3_helper@fix-mounting
+        uses: qualcomm-linux/video-driver/.github/actions/aws_s3_helper@fix-mounting-3
         with:
           s3_bucket: qli-prd-video-gh-artifacts
           local_file: ${{ github.workspace }}/v4l-video-test-app/${{ matrix.build_matrix.machine }}_irisTestApp.tar.gz
           mode: single-upload
         env:
           machine: "${{ matrix.build_matrix.machine }}"
-
+        
       - name: Clean up
         run: |
           rm -rf ${{ github.workspace }}/artifacts
@@ -124,4 +127,3 @@ jobs:
             summary=":x: Build Failed for ${{ matrix.build_matrix.machine }}"
           fi
           echo -e "<details><summary><i>Build Summary</i></summary>\n${summary}\n</details>" >> $GITHUB_STEP_SUMMARY
- 
